name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Check format (prettier)
        run: yarn format-check

      - name: Lint (eslint)
        run: yarn lint-check

      - name: Compile
        run: yarn build

      - name: Test
        run: yarn test

      - name: Publish docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: splash
          dockerfile: Dockerfile.prod
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.online.ntnu.no
          tag_names: true
#
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: eu-west-1
#      - name: Run Codepipeline
#        run: aws codepipeline start-pipeline-execution --name SplashPipeline

